baseURL = "https://lubieniebieski.pl"
languageCode = "en-us"
theme = "terminal"

title = "lubieniebieski by adam nowak"

[params]
  centerTheme = true
  themeColor = "blue"
  favicon = "favicon.ico"
  ogimage = "favicon-512.png"
  appleTouchIcon = "apple-touch-icon.png"
  subtitle = "made with ğŸ’™"
  [params.logo]
    logoText = "lubieniebieski // adam nowak"
    logoHomeLink = "/"

[languages]
  [languages.en]
    languageName = "English"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "blog"
        name = "âœï¸"
        url = "/"
        weight = 1

      [[languages.en.menu.main]]
        identifier = "cyks"
        name = "ğŸ“¸"
        url = "/categories/cyk"
        weight = 2

      [[languages.en.menu.main]]
        identifier = "about"
        name = "ğŸ’ğŸ»â€â™‚ï¸"
        url = "/about"
        weight = 3